release_linux_x86_64_download_docker_builder:
  timeout_in: 120m
  out_release_linux_x86_64_cache:
    folder: out
    fingerprint_script:
      - "echo out_release_linux_x86_64"
    reupload_on_changes: true
    populate_script:
      - "mkdir -p out"
  git_release_linux_x86_64_cache:
    folder: git_clones
    fingerprint_script:
      - "echo git_release_linux_x86_64"
    reupload_on_changes: true
    populate_script:
      - "mkdir -p git_clones"
  build_script:
    - "./tools/cirrus_build_project.sh ncdns release linux x86_64 0"

release_linux_x86_64_goeasyconfig_docker_builder:
  timeout_in: 120m
  out_release_linux_x86_64_cache:
    folder: out
    fingerprint_script:
      - "echo out_release_linux_x86_64"
    reupload_on_changes: true
    populate_script:
      - "mkdir -p out"
  git_release_linux_x86_64_cache:
    folder: git_clones
    fingerprint_script:
      - "echo git_release_linux_x86_64"
    reupload_on_changes: true
    populate_script:
      - "mkdir -p git_clones"
  build_script:
    - "./tools/cirrus_build_project.sh goeasyconfig release linux x86_64 1"
  depends_on:
    - "release_linux_x86_64_download"

release_linux_x86_64_ncdns_docker_builder:
  timeout_in: 120m
  out_release_linux_x86_64_cache:
    folder: out
    fingerprint_script:
      - "echo out_release_linux_x86_64"
    reupload_on_changes: true
    populate_script:
      - "mkdir -p out"
  git_release_linux_x86_64_cache:
    folder: git_clones
    fingerprint_script:
      - "echo git_release_linux_x86_64"
    reupload_on_changes: true
    populate_script:
      - "mkdir -p git_clones"
  build_script:
    - "./tools/cirrus_build_project.sh ncdns release linux x86_64 1"
  depends_on:
    - "release_linux_x86_64_goeasyconfig"

release_linux_x86_64_ncp11_docker_builder:
  timeout_in: 120m
  out_release_linux_x86_64_cache:
    folder: out
    fingerprint_script:
      - "echo out_release_linux_x86_64"
    reupload_on_changes: true
    populate_script:
      - "mkdir -p out"
  git_release_linux_x86_64_cache:
    folder: git_clones
    fingerprint_script:
      - "echo git_release_linux_x86_64"
    reupload_on_changes: true
    populate_script:
      - "mkdir -p git_clones"
  build_script:
    - "./tools/cirrus_build_project.sh ncp11 release linux x86_64 1"
  depends_on:
    - "release_linux_x86_64_ncdns"

release_linux_x86_64_ncprop279_docker_builder:
  timeout_in: 120m
  out_release_linux_x86_64_cache:
    folder: out
    fingerprint_script:
      - "echo out_release_linux_x86_64"
    reupload_on_changes: true
    populate_script:
      - "mkdir -p out"
  git_release_linux_x86_64_cache:
    folder: git_clones
    fingerprint_script:
      - "echo git_release_linux_x86_64"
    reupload_on_changes: true
    populate_script:
      - "mkdir -p git_clones"
  build_script:
    - "./tools/cirrus_build_project.sh ncprop279 release linux x86_64 1"
  depends_on:
    - "release_linux_x86_64_ncp11"

release_linux_x86_64_plain-binaries_docker_builder:
  timeout_in: 120m
  out_release_linux_x86_64_cache:
    folder: out
    fingerprint_script:
      - "echo out_release_linux_x86_64"
    reupload_on_changes: true
    populate_script:
      - "mkdir -p out"
  git_release_linux_x86_64_cache:
    folder: git_clones
    fingerprint_script:
      - "echo git_release_linux_x86_64"
    reupload_on_changes: true
    populate_script:
      - "mkdir -p git_clones"
  build_script:
    - "./tools/cirrus_build_project.sh plain-binaries release linux x86_64 1"
  depends_on:
    - "release_linux_x86_64_ncprop279"

release_linux_x86_64_release_docker_builder:
  timeout_in: 120m
  out_release_linux_x86_64_cache:
    folder: out
    fingerprint_script:
      - "echo out_release_linux_x86_64"
    reupload_on_changes: true
    populate_script:
      - "mkdir -p out"
  git_release_linux_x86_64_cache:
    folder: git_clones
    fingerprint_script:
      - "echo git_release_linux_x86_64"
    reupload_on_changes: true
    populate_script:
      - "mkdir -p git_clones"
  build_script:
    - "./tools/cirrus_build_project.sh release release linux x86_64 1"
  depends_on:
    - "release_linux_x86_64_plain-binaries"

release_linux_i686_download_docker_builder:
  timeout_in: 120m
  out_release_linux_i686_cache:
    folder: out
    fingerprint_script:
      - "echo out_release_linux_i686"
    reupload_on_changes: true
    populate_script:
      - "mkdir -p out"
  git_release_linux_i686_cache:
    folder: git_clones
    fingerprint_script:
      - "echo git_release_linux_i686"
    reupload_on_changes: true
    populate_script:
      - "mkdir -p git_clones"
  build_script:
    - "./tools/cirrus_build_project.sh ncdns release linux i686 0"

release_linux_i686_goeasyconfig_docker_builder:
  timeout_in: 120m
  out_release_linux_i686_cache:
    folder: out
    fingerprint_script:
      - "echo out_release_linux_i686"
    reupload_on_changes: true
    populate_script:
      - "mkdir -p out"
  git_release_linux_i686_cache:
    folder: git_clones
    fingerprint_script:
      - "echo git_release_linux_i686"
    reupload_on_changes: true
    populate_script:
      - "mkdir -p git_clones"
  build_script:
    - "./tools/cirrus_build_project.sh goeasyconfig release linux i686 1"
  depends_on:
    - "release_linux_i686_download"

release_linux_i686_ncdns_docker_builder:
  timeout_in: 120m
  out_release_linux_i686_cache:
    folder: out
    fingerprint_script:
      - "echo out_release_linux_i686"
    reupload_on_changes: true
    populate_script:
      - "mkdir -p out"
  git_release_linux_i686_cache:
    folder: git_clones
    fingerprint_script:
      - "echo git_release_linux_i686"
    reupload_on_changes: true
    populate_script:
      - "mkdir -p git_clones"
  build_script:
    - "./tools/cirrus_build_project.sh ncdns release linux i686 1"
  depends_on:
    - "release_linux_i686_goeasyconfig"

release_linux_i686_ncp11_docker_builder:
  timeout_in: 120m
  out_release_linux_i686_cache:
    folder: out
    fingerprint_script:
      - "echo out_release_linux_i686"
    reupload_on_changes: true
    populate_script:
      - "mkdir -p out"
  git_release_linux_i686_cache:
    folder: git_clones
    fingerprint_script:
      - "echo git_release_linux_i686"
    reupload_on_changes: true
    populate_script:
      - "mkdir -p git_clones"
  build_script:
    - "./tools/cirrus_build_project.sh ncp11 release linux i686 1"
  depends_on:
    - "release_linux_i686_ncdns"

release_linux_i686_ncprop279_docker_builder:
  timeout_in: 120m
  out_release_linux_i686_cache:
    folder: out
    fingerprint_script:
      - "echo out_release_linux_i686"
    reupload_on_changes: true
    populate_script:
      - "mkdir -p out"
  git_release_linux_i686_cache:
    folder: git_clones
    fingerprint_script:
      - "echo git_release_linux_i686"
    reupload_on_changes: true
    populate_script:
      - "mkdir -p git_clones"
  build_script:
    - "./tools/cirrus_build_project.sh ncprop279 release linux i686 1"
  depends_on:
    - "release_linux_i686_ncp11"

release_linux_i686_plain-binaries_docker_builder:
  timeout_in: 120m
  out_release_linux_i686_cache:
    folder: out
    fingerprint_script:
      - "echo out_release_linux_i686"
    reupload_on_changes: true
    populate_script:
      - "mkdir -p out"
  git_release_linux_i686_cache:
    folder: git_clones
    fingerprint_script:
      - "echo git_release_linux_i686"
    reupload_on_changes: true
    populate_script:
      - "mkdir -p git_clones"
  build_script:
    - "./tools/cirrus_build_project.sh plain-binaries release linux i686 1"
  depends_on:
    - "release_linux_i686_ncprop279"

release_linux_i686_release_docker_builder:
  timeout_in: 120m
  out_release_linux_i686_cache:
    folder: out
    fingerprint_script:
      - "echo out_release_linux_i686"
    reupload_on_changes: true
    populate_script:
      - "mkdir -p out"
  git_release_linux_i686_cache:
    folder: git_clones
    fingerprint_script:
      - "echo git_release_linux_i686"
    reupload_on_changes: true
    populate_script:
      - "mkdir -p git_clones"
  build_script:
    - "./tools/cirrus_build_project.sh release release linux i686 1"
  depends_on:
    - "release_linux_i686_plain-binaries"

release_windows_x86_64_download_docker_builder:
  timeout_in: 120m
  out_release_windows_x86_64_cache:
    folder: out
    fingerprint_script:
      - "echo out_release_windows_x86_64"
    reupload_on_changes: true
    populate_script:
      - "mkdir -p out"
  git_release_windows_x86_64_cache:
    folder: git_clones
    fingerprint_script:
      - "echo git_release_windows_x86_64"
    reupload_on_changes: true
    populate_script:
      - "mkdir -p git_clones"
  build_script:
    - "./tools/cirrus_build_project.sh ncdns release windows x86_64 0"

release_windows_x86_64_goeasyconfig_docker_builder:
  timeout_in: 120m
  out_release_windows_x86_64_cache:
    folder: out
    fingerprint_script:
      - "echo out_release_windows_x86_64"
    reupload_on_changes: true
    populate_script:
      - "mkdir -p out"
  git_release_windows_x86_64_cache:
    folder: git_clones
    fingerprint_script:
      - "echo git_release_windows_x86_64"
    reupload_on_changes: true
    populate_script:
      - "mkdir -p git_clones"
  build_script:
    - "./tools/cirrus_build_project.sh goeasyconfig release windows x86_64 1"
  depends_on:
    - "release_windows_x86_64_download"

release_windows_x86_64_ncdns_docker_builder:
  timeout_in: 120m
  out_release_windows_x86_64_cache:
    folder: out
    fingerprint_script:
      - "echo out_release_windows_x86_64"
    reupload_on_changes: true
    populate_script:
      - "mkdir -p out"
  git_release_windows_x86_64_cache:
    folder: git_clones
    fingerprint_script:
      - "echo git_release_windows_x86_64"
    reupload_on_changes: true
    populate_script:
      - "mkdir -p git_clones"
  build_script:
    - "./tools/cirrus_build_project.sh ncdns release windows x86_64 1"
  depends_on:
    - "release_windows_x86_64_goeasyconfig"

release_windows_x86_64_ncp11_docker_builder:
  timeout_in: 120m
  out_release_windows_x86_64_cache:
    folder: out
    fingerprint_script:
      - "echo out_release_windows_x86_64"
    reupload_on_changes: true
    populate_script:
      - "mkdir -p out"
  git_release_windows_x86_64_cache:
    folder: git_clones
    fingerprint_script:
      - "echo git_release_windows_x86_64"
    reupload_on_changes: true
    populate_script:
      - "mkdir -p git_clones"
  build_script:
    - "./tools/cirrus_build_project.sh ncp11 release windows x86_64 1"
  depends_on:
    - "release_windows_x86_64_ncdns"

release_windows_x86_64_ncprop279_docker_builder:
  timeout_in: 120m
  out_release_windows_x86_64_cache:
    folder: out
    fingerprint_script:
      - "echo out_release_windows_x86_64"
    reupload_on_changes: true
    populate_script:
      - "mkdir -p out"
  git_release_windows_x86_64_cache:
    folder: git_clones
    fingerprint_script:
      - "echo git_release_windows_x86_64"
    reupload_on_changes: true
    populate_script:
      - "mkdir -p git_clones"
  build_script:
    - "./tools/cirrus_build_project.sh ncprop279 release windows x86_64 1"
  depends_on:
    - "release_windows_x86_64_ncp11"

release_windows_x86_64_plain-binaries_docker_builder:
  timeout_in: 120m
  out_release_windows_x86_64_cache:
    folder: out
    fingerprint_script:
      - "echo out_release_windows_x86_64"
    reupload_on_changes: true
    populate_script:
      - "mkdir -p out"
  git_release_windows_x86_64_cache:
    folder: git_clones
    fingerprint_script:
      - "echo git_release_windows_x86_64"
    reupload_on_changes: true
    populate_script:
      - "mkdir -p git_clones"
  build_script:
    - "./tools/cirrus_build_project.sh plain-binaries release windows x86_64 1"
  depends_on:
    - "release_windows_x86_64_ncprop279"

release_windows_x86_64_release_docker_builder:
  timeout_in: 120m
  out_release_windows_x86_64_cache:
    folder: out
    fingerprint_script:
      - "echo out_release_windows_x86_64"
    reupload_on_changes: true
    populate_script:
      - "mkdir -p out"
  git_release_windows_x86_64_cache:
    folder: git_clones
    fingerprint_script:
      - "echo git_release_windows_x86_64"
    reupload_on_changes: true
    populate_script:
      - "mkdir -p git_clones"
  build_script:
    - "./tools/cirrus_build_project.sh release release windows x86_64 1"
  depends_on:
    - "release_windows_x86_64_plain-binaries"

release_windows_i686_download_docker_builder:
  timeout_in: 120m
  out_release_windows_i686_cache:
    folder: out
    fingerprint_script:
      - "echo out_release_windows_i686"
    reupload_on_changes: true
    populate_script:
      - "mkdir -p out"
  git_release_windows_i686_cache:
    folder: git_clones
    fingerprint_script:
      - "echo git_release_windows_i686"
    reupload_on_changes: true
    populate_script:
      - "mkdir -p git_clones"
  build_script:
    - "./tools/cirrus_build_project.sh ncdns release windows i686 0"

release_windows_i686_goeasyconfig_docker_builder:
  timeout_in: 120m
  out_release_windows_i686_cache:
    folder: out
    fingerprint_script:
      - "echo out_release_windows_i686"
    reupload_on_changes: true
    populate_script:
      - "mkdir -p out"
  git_release_windows_i686_cache:
    folder: git_clones
    fingerprint_script:
      - "echo git_release_windows_i686"
    reupload_on_changes: true
    populate_script:
      - "mkdir -p git_clones"
  build_script:
    - "./tools/cirrus_build_project.sh goeasyconfig release windows i686 1"
  depends_on:
    - "release_windows_i686_download"

release_windows_i686_ncdns_docker_builder:
  timeout_in: 120m
  out_release_windows_i686_cache:
    folder: out
    fingerprint_script:
      - "echo out_release_windows_i686"
    reupload_on_changes: true
    populate_script:
      - "mkdir -p out"
  git_release_windows_i686_cache:
    folder: git_clones
    fingerprint_script:
      - "echo git_release_windows_i686"
    reupload_on_changes: true
    populate_script:
      - "mkdir -p git_clones"
  build_script:
    - "./tools/cirrus_build_project.sh ncdns release windows i686 1"
  depends_on:
    - "release_windows_i686_goeasyconfig"

release_windows_i686_ncp11_docker_builder:
  timeout_in: 120m
  out_release_windows_i686_cache:
    folder: out
    fingerprint_script:
      - "echo out_release_windows_i686"
    reupload_on_changes: true
    populate_script:
      - "mkdir -p out"
  git_release_windows_i686_cache:
    folder: git_clones
    fingerprint_script:
      - "echo git_release_windows_i686"
    reupload_on_changes: true
    populate_script:
      - "mkdir -p git_clones"
  build_script:
    - "./tools/cirrus_build_project.sh ncp11 release windows i686 1"
  depends_on:
    - "release_windows_i686_ncdns"

release_windows_i686_ncprop279_docker_builder:
  timeout_in: 120m
  out_release_windows_i686_cache:
    folder: out
    fingerprint_script:
      - "echo out_release_windows_i686"
    reupload_on_changes: true
    populate_script:
      - "mkdir -p out"
  git_release_windows_i686_cache:
    folder: git_clones
    fingerprint_script:
      - "echo git_release_windows_i686"
    reupload_on_changes: true
    populate_script:
      - "mkdir -p git_clones"
  build_script:
    - "./tools/cirrus_build_project.sh ncprop279 release windows i686 1"
  depends_on:
    - "release_windows_i686_ncp11"

release_windows_i686_plain-binaries_docker_builder:
  timeout_in: 120m
  out_release_windows_i686_cache:
    folder: out
    fingerprint_script:
      - "echo out_release_windows_i686"
    reupload_on_changes: true
    populate_script:
      - "mkdir -p out"
  git_release_windows_i686_cache:
    folder: git_clones
    fingerprint_script:
      - "echo git_release_windows_i686"
    reupload_on_changes: true
    populate_script:
      - "mkdir -p git_clones"
  build_script:
    - "./tools/cirrus_build_project.sh plain-binaries release windows i686 1"
  depends_on:
    - "release_windows_i686_ncprop279"

release_windows_i686_release_docker_builder:
  timeout_in: 120m
  out_release_windows_i686_cache:
    folder: out
    fingerprint_script:
      - "echo out_release_windows_i686"
    reupload_on_changes: true
    populate_script:
      - "mkdir -p out"
  git_release_windows_i686_cache:
    folder: git_clones
    fingerprint_script:
      - "echo git_release_windows_i686"
    reupload_on_changes: true
    populate_script:
      - "mkdir -p git_clones"
  build_script:
    - "./tools/cirrus_build_project.sh release release windows i686 1"
  depends_on:
    - "release_windows_i686_plain-binaries"

release_osx_x86_64_download_docker_builder:
  timeout_in: 120m
  out_release_osx_x86_64_cache:
    folder: out
    fingerprint_script:
      - "echo out_release_osx_x86_64"
    reupload_on_changes: true
    populate_script:
      - "mkdir -p out"
  git_release_osx_x86_64_cache:
    folder: git_clones
    fingerprint_script:
      - "echo git_release_osx_x86_64"
    reupload_on_changes: true
    populate_script:
      - "mkdir -p git_clones"
  build_script:
    - "./tools/cirrus_build_project.sh ncdns release osx x86_64 0"

