release_linux_x86_64_download_docker_builder:
  timeout_in: 120m
  out_release_linux_x86_64_cache:
    folder: out
    fingerprint_script:
      - "echo out_release_linux_x86_64"
    reupload_on_changes: true
    populate_script:
      - "mkdir -p out"
  git_release_linux_x86_64_cache:
    folder: git_clones
    fingerprint_script:
      - "echo git_release_linux_x86_64"
    reupload_on_changes: true
    populate_script:
      - "mkdir -p git_clones"
  build_script:
    - "./tools/cirrus_build_project.sh ncdns release linux x86_64 0"

release_linux_x86_64_goeasyconfig_docker_builder:
  timeout_in: 120m
  out_release_linux_x86_64_cache:
    folder: out
    fingerprint_script:
      - "echo out_release_linux_x86_64"
    reupload_on_changes: true
    populate_script:
      - "mkdir -p out"
  git_release_linux_x86_64_cache:
    folder: git_clones
    fingerprint_script:
      - "echo git_release_linux_x86_64"
    reupload_on_changes: true
    populate_script:
      - "mkdir -p git_clones"
  build_script:
    - "./tools/cirrus_build_project.sh goeasyconfig release linux x86_64 1"
  depends_on:
    - "release_linux_x86_64_download"

release_linux_x86_64_ncdns_docker_builder:
  timeout_in: 120m
  out_release_linux_x86_64_cache:
    folder: out
    fingerprint_script:
      - "echo out_release_linux_x86_64"
    reupload_on_changes: true
    populate_script:
      - "mkdir -p out"
  git_release_linux_x86_64_cache:
    folder: git_clones
    fingerprint_script:
      - "echo git_release_linux_x86_64"
    reupload_on_changes: true
    populate_script:
      - "mkdir -p git_clones"
  build_script:
    - "./tools/cirrus_build_project.sh ncdns release linux x86_64 1"
  depends_on:
    - "release_linux_x86_64_goeasyconfig"

release_linux_x86_64_ncp11_docker_builder:
  timeout_in: 120m
  out_release_linux_x86_64_cache:
    folder: out
    fingerprint_script:
      - "echo out_release_linux_x86_64"
    reupload_on_changes: true
    populate_script:
      - "mkdir -p out"
  git_release_linux_x86_64_cache:
    folder: git_clones
    fingerprint_script:
      - "echo git_release_linux_x86_64"
    reupload_on_changes: true
    populate_script:
      - "mkdir -p git_clones"
  build_script:
    - "./tools/cirrus_build_project.sh ncp11 release linux x86_64 1"
  depends_on:
    - "release_linux_x86_64_ncdns"

release_linux_x86_64_ncprop279_docker_builder:
  timeout_in: 120m
  out_release_linux_x86_64_cache:
    folder: out
    fingerprint_script:
      - "echo out_release_linux_x86_64"
    reupload_on_changes: true
    populate_script:
      - "mkdir -p out"
  git_release_linux_x86_64_cache:
    folder: git_clones
    fingerprint_script:
      - "echo git_release_linux_x86_64"
    reupload_on_changes: true
    populate_script:
      - "mkdir -p git_clones"
  build_script:
    - "./tools/cirrus_build_project.sh ncprop279 release linux x86_64 1"
  depends_on:
    - "release_linux_x86_64_ncp11"

